apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/composition-resource-name: bucket-configmap-0
  generateName: example-
  labels:
    crossplane.io/composite: example
  ownerReferences:
    - apiVersion: example.crossplane.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: XR
      name: example
      uid: ""
spec:
  forProvider:
    manifest:
      apiVersion: v1
      data:
        bucket: random-bucket-id
      kind: ConfigMap
      metadata:
        name: my-awesome-dev-bucket-bucket
  providerConfigRef:
    name: kubernetes
