apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: website
spec:
  components:
    - name: frontend
      type: webservice
      properties:
        image: oamdev/testapp:v1
        env: # TODO: templatize env
          - name: FOO
            value: bar
        port: 8080 # TODO: templatize port
      traits:
        - type: annotations
          properties:
            foo: bar # TODO: templatize annotations
        - type: gateway
          properties:
            domain: localhost
            http:
              - path: "/"
                port: 8080 # TODO: templatize port
