apiVersion: example.crossplane.io/v1beta1
kind: XR
metadata:
  name: example
status:
  conditions:
    - lastTransitionTime: "2024-01-01T00:00:00Z"
      message: "Unready resources: bucket-configmap-0"
      reason: Creating
      status: "False"
      type: Ready
  dummy: cool-status
---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  annotations:
    crossplane.io/composition-resource-name: bucket-configmap-0
  generateName: example-
  labels:
    crossplane.io/composite: example
  ownerReferences:
    - apiVersion: example.crossplane.io/v1beta1
      blockOwnerDeletion: true
      controller: true
      kind: XR
      name: example
      uid: ""
spec:
  forProvider:
    manifest:
      apiVersion: v1
      data:
        bucket: random-bucket-id
      kind: ConfigMap
      metadata:
        name: (join('-', ['my-awesome', $environment, 'bucket-bucket'])) # Templated for reuse between test cases
  providerConfigRef:
    name: kubernetes
